# Generated by Django 4.2.11 on 2024-05-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default_img/user.png', null=True, upload_to='users/'),
        ),
    ]
